# Site settings
title: Log4j.properties
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://log4j.properties" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
